name: Build macOS App

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Dependencies
      env:
        npm_config_runtime: electron
        npm_config_target: 35.7.5
        npm_config_disturl: https://electronjs.org/headers
      run: npm install

    - name: Build macOS App
      run: npm run build
      
    - name: Build App DMG package
      run: npx electron-builder --mac

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: OpenTerm-macOS
        path: dist/*.dmg
